function plot_expected_answer(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Mar-2022 21:33:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

xlim([0, 30])
ylim([0, 0.3])

% Create multiple lines using matrix input to plot
plot1 = plot(X1,Y1, X2, Y2);
set(plot1(1),'DisplayName','Expected Radiance');
set(plot1(2),'DisplayName','Computed Radiance');

% Create ylabel
ylabel('Radiance','FontSize',20,'Interpreter','latex');

% Create xlabel
xlabel('Number of Bounces','FontSize',20,'Interpreter','latex');

% Create title
title('Computed vs Expected Radiance','FontSize',20,'Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.494229182490593 0.141350826044701 0.391171264648437 0.148688046647227],...
    'Interpreter','latex',...
    'FontSize',20,...
    'FontName','Helvetica Neue');

