function plot_compare_variances(X1, Y1, X2, Y2)

%
PLOT_COMPARED_VARIANCES(X1, Y1, X2, Y2
)
%  X1:
vector of
x data
%  Y1:
vector of
y data
%  X2:
vector of
x data
%  Y2:
vector of
y data

%  Auto-
generated by
MATLAB on
28-Mar-2022 11:59:24

%
Create figure
figure1 = figure;

%
Create axes
axes1 = axes('Parent', figure1);
hold(axes1,
'on');

%
Create multiple
lines using
matrix input
to loglog
loglog1 = loglog(X1, Y1, X2, Y2);

set (loglog1(

1),'DisplayName','No Russian Roulette','Color',[1 0 0]);

set (loglog1(

2),'DisplayName','Russian Roulette','Color',[0 0 0]);

hold(axes1,
'off');
%
Set the
remaining axes

properties
set(axes1,

'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');
%
Create legend
legend1 = legend(axes1, 'show');
set(legend1, ...
'Location','northeast',...
'FontSize',20,...
'FontName','Helvetica Neue', 'Interpreter', 'latex');

